### ISSUE TITLE
Feature Suggestion - Move Multiple Tabs

### ISSUE THREAD

**Issue by Cr8zyIvan** [MorganTwoZero/move-tab#1]
Awesome Extension!

I'm assuming this is the "Move tab to the last window" Extension Page (for Firefox Extensions).

I would love to be able to move Multiple Tabs to the Last Active Window, all the Selected Tabs that is.

Thanks, Cheers!

**Comment by MorganTwoZero** [comment]
Thank you for the kind words! 

As for your suggestion, i'm not against it, but i don't think that it's possible to achieve this from an extension side. I'm presuming that by "all the Selected Tabs" you mean selected via Ctrl/Shift + click on the tab bar? The problem is that there isn't an API to query the tab bar (or i just failed to find one). 

I think your best option here is to find some alternative tab bar extension (Sidebery, Tree Style Tab, etc.) with such functionality, or implement it yourself.

**Comment by Cr8zyIvan** [comment]
I use other Extensions that execute functions on multiple Tabs (Like Duplicate Tabs {Extension name: Duplicate Tab Shortcut by Stefan Sundin} or Pop Out Tabs into a New Window {Extension name: Tab Shortcuts by Marijn Kok}). There aren't that many though, and I have heard that it isn't an obvious thing to do. I don't know how these ones have gone about it either. In any case, thank you to have considered my Suggestion. Cheers!
